apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: sendmail
  labels:
    app.kubernetes.io/version: "0.3"
  annotations:
    tekton.dev/pipelines.minVersion: "0.28.0"
    tekton.dev/categories: Notification Tools
    tekton.dev/tags: notification-tool
    tekton.dev/displayName: "Send email notification"    
spec:
  description: >-
    This task send email notification using SMTP Server
  params:
    - name: git_repo
      description: Git repository full name.
    - name: git_commit
      description: Git commit.
    - name: git_branch
      description: Git branch.   
    - name: pusher_name
      description: Git pusher's name.
    - name: pusher_email
      description: Git pusher's email.                 
    - name: pipelinerun_status
      description: PipelineRun status.
    - name: pipelinerun_name
      description: PipelineRun name.
    - name: namespace
      description: Application namespace.
    - name: sendmail_secret
      description: SMTP or API credentials.    
    - name: send_method
      description: "Method to send email. Valid values: (SMTP|API). Default: SMTP."
      default: "SMTP"              
    - name: from
      description: Sender email addresses.
    - name: recipients
      description: Recipient email address list separated by space or a group.
    - name: subject
      description: Email subject.         

  steps:
  - name: send-message
    image: docker.io/kubeideas/sendmail:v0.3.0
    env:
      - name: "GIT_REPO"
        value: $(params.git_repo)
      - name: "GIT_COMMIT"
        value: $(params.git_commit)
      - name: "GIT_BRANCH"
        value: $(params.git_branch)
      - name: "PUSHER_NAME"
        value: $(params.pusher_name)
      - name: "PUSHER_EMAIL"
        value: $(params.pusher_email)
      - name: "PIPELINERUN_STATUS"
        value: $(params.pipelinerun_status)
      - name: "PIPELINERUN_NAME"
        value: $(params.pipelinerun_name)
      - name: "NAMESPACE"
        value: $(params.namespace)
      - name: "SEND_METHOD"
        value: $(params.send_method)
      - name: "FROM"
        value: $(params.from)
      - name: "RECIPIENTS"
        value: $(params.recipients)
      - name: "SUBJECT"
        value: $(params.subject)
    envFrom:
      - secretRef:
          name: $(params.sendmail_secret)
