apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: books-trigger-template
spec:
  params:
  - name: git_url
    description: git repository URL.
  - name: git_commit
    description: Git commit.
  - name: description
    description: Helm installation description.
  - name: image_tag
    description: Image tag   
  - name: git_repo
    description: Git repository full name.
  - name: git_branch
    description: Git branch.
  - name: pusher_name
    description: Git pusher name. 
  - name: pusher_email
    description: Git pusher email.
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      generateName: books-golang-pipeline-run-
    spec:
      serviceAccountName: tekton-triggers    
      pipelineRef:
        name: golang-pipeline
      params:
      - name: git_url
        value: $(tt.params.git_url)
      - name: git_commit
        value: $(tt.params.git_commit)        
      - name: chart_repo_url
        value: https://antonio-tolentino.github.io/charts/
      - name: chart_name
        value: generic
      - name: chart_version
        value: "1.1.0"   
      - name: release_deploy
        value: books
      - name: description
        value: $(tt.params.description)      
      - name: namespace
        value: tekton-tests
      - name: helm_custom_file
        value: helm.yaml
      - name: image_repo
        value: tolentino/books
      - name: image_tag 
        value: $(tt.params.image_tag)    
      - name: enable_notifications
        value: "true"
      - name: git_repo
        value: $(tt.params.git_repo)
      - name: git_branch
        value: $(tt.params.git_branch)
      - name: pusher_name
        value: $(tt.params.pusher_name)
      - name: pusher_email
        value: $(tt.params.pusher_email)
      - name: recipients
        value: atcjunior@gmail.com
      workspaces:
      - name: github-ssh
        secret:
          secretName: github-ssh
      - name: code-ws
        persistentVolumeClaim:
          claimName: books-pipeline