apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: m2-cache
  namespace: develop
spec:
  storageClassName: tekton-gp2
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
