apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: aws-cli
  labels:
    app.kubernetes.io/version: "0.1"
  annotations:
    tekton.dev/pipelines.minVersion: "0.27.1"
    tekton.dev/categories: Cloud SDK
    tekton.dev/tags: "aws, sdk, cli"
    tekton.dev/displayName: "AWS SDK client"    
spec:
  description: |
    This task execute actions on AWS resources
 
  steps:
  - name: clean-old-images
    image: docker.io/amazon/aws-cli:2.2.42
    args: ["secretsmanager","describe-secret", "--secret-id", "mysecret"]
