apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: slack
  labels:
    app.kubernetes.io/version: "0.2"
  annotations:
    tekton.dev/pipelines.minVersion: "0.28.0"
    tekton.dev/categories: Notification Tools
    tekton.dev/tags: notification-tool
    tekton.dev/displayName: "Send message to slack channel"    
spec:
  description: |
    This task send messages to slack channel
  params:
    - name: git_repo
      description: Git repository full name.
    - name: git_commit
      description: Git commit.
    - name: git_branch
      description: Git branch.
    - name: pusher_name
      description: Git pusher's name.
    - name: pusher_email
      description: Git pusher's email.
    - name: pipelinerun_status
      description: PipelineRun status.
    - name: pipelinerun_name
      description: PipelineRun name.
    - name: namespace
      description: Application namespace.
    - name: channel
      description: Slack Channel.
    - name: slack_secret
      description: Slack token secret.

  steps:
  - name: send-message
    image: kubeideas/slack:v0.1.0
    env:
      - name: "GIT_REPO"
        value: $(params.git_repo)
      - name: "GIT_COMMIT"
        value: $(params.git_commit)
      - name: "GIT_BRANCH"
        value: $(params.git_branch)
      - name: "PUSHER_NAME"
        value: $(params.pusher_name)
      - name: "PUSHER_EMAIL"
        value: $(params.pusher_email)
      - name: "PIPELINERUN_STATUS"
        value: $(params.pipelinerun_status)
      - name: "PIPELINERUN_NAME"
        value: $(params.pipelinerun_name)
      - name: "NAMESPACE"
        value: $(params.namespace)
      - name: "CHANNEL"
        value: $(params.channel)        
    envFrom:
      - secretRef:
          name: $(params.slack_secret)   
