apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: books-pipeline
spec:
  storageClassName: tekton-kind
  resources:
    requests:
      storage: 100Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce 
