apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tekton-triggers-minimal
  namespace: tekton-tests
rules:
# secrets are only needed for GitHub/GitLab interceptors
# configmaps is needed for updating logging config
- apiGroups: 
  - ""
  resources: 
  - configmaps
  - secrets
  verbs: 
  - get
  - list
  - watch
- apiGroups: 
  - triggers.tekton.dev
  resources: 
  - eventlisteners
  - triggerbindings
  - triggertemplates
  - triggers
  verbs: 
  - get
  - list
  - watch
# Permissions on resources in associated TriggerTemplates
- apiGroups: 
  - tekton.dev
  resources: 
  - pipelineruns
  - taskruns
  verbs: 
  - create
  - list
  - delete  
- apiGroups: 
  - ""
  resources: 
  - serviceaccounts
  verbs: 
  - impersonate
- apiGroups: 
  - policy
  resources: 
  - podsecuritypolicies
  resourceNames: 
  - tekton-triggers
  verbs: 
  - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tekton-triggers-binding
  namespace: tekton-tests
subjects:
- kind: ServiceAccount
  name: tekton-triggers
  namespace: tekton-tests
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: tekton-triggers-minimal 
