apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kaniko-image-cache
  labels:
    app: kaniko
spec:
  storageClassName: tekton-kind
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
