apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tekton-developer
  namespace: develop
rules:
- apiGroups: 
  - triggers.tekton.dev
  resources:
  - pipelines
  - pipelineruns
  - tasks
  - taskruns
  - eventlisteners
  - triggerbindings
  - triggertemplates
  - triggers
  - pipelineresources
  verbs: 
  - get
  - list
  - watch

---
  
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tekton-developer
  namespace: develop
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: tekton-developer
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: tekton-developer
